### ISSUE TITLE
Truncate messages to fit maximum length limitation

### ISSUE THREAD

**Issue by muety** [muety/telepush#66]
Discussed in #65. Roughly copy alertmanager's implementation. Also, add a config option so that a server admin can choose whether to reject too long messages (as it's currently the case) or truncate them.

**Comment by darkfessing** [comment]
Looks like nothing changed? Or just telepush.dev was not updated?

`ts=2023-12-28T18:11:28.857Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=4 err="telepush/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: https://telepush.dev/api/inlets/alertmanager/XXXXXX: message too long (max is 4096 characters)"
ts=2023-12-28T18:11:28.901Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=4 err="telepush/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: https://telepush.dev/api/inlets/alertmanager/XXXXXX: message too long (max is 4096 characters)"
ts=2023-12-28T18:11:28.901Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=8 err="telepush/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: https://telepush.dev/api/inlets/alertmanager/XXXXXX: message too long (max is 4096 characters)"
ts=2023-12-28T18:11:28.903Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=4 err="telepush/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: https://telepush.dev/api/inlets/alertmanager/XXXXXX: message too long (max is 4096 characters)"
ts=2023-12-28T18:11:28.948Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=8 err="telepush/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: https://telepush.dev/api/inlets/alertmanager/XXXXXX: message too long (max is 4096 characters)"
ts=2023-12-28T18:11:28.948Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=8 err="telepush/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: https://telepush.dev/api/inlets/alertmanager/XXXXXX: message too long (max is 4096 characters)"
ts=2023-12-28T18:11:28.948Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=8 err="telepush/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: https://telepush.dev/api/inlets/alertmanager/XXXXXX: message too long (max is 4096 characters)"
ts=2023-12-28T18:11:28.949Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=8 err="telepush/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: https://telepush.dev/api/inlets/alertmanager/XXXXXX: message too long (max is 4096 characters)"
ts=2023-12-28T18:11:28.992Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=4 err="telepush/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: https://telepush.dev/api/inlets/alertmanager/XXXXXX: message too long (max is 4096 characters)"
ts=2023-12-28T18:11:28.993Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=8 err="telepush/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: https://telepush.dev/api/inlets/alertmanager/XXXXXX: message too long (max is 4096 characters)"`

**Comment by muety** [comment]
Telepush.dev has the truncation feature disabled, it will continue rejecting too long messages.

**Comment by darkfessing** [comment]
Ohh i get it. Able to use it by building my own telepush docker image (current release don`t include new -truncateMsgs option). And launch it in local network (in pool mode).

But I got some new errors. Looks like it is related to new -truncateMsgs feature.. or something else?

alertmanager error:
`ts=2023-12-28T19:29:28.997Z caller=dispatch.go:352 level=error component=dispatcher msg="Notify for alerts failed" num_alerts=3 err="telepush/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: http://1.1.X.XXX:8080/api/inlets/alertmanager/XXXXX: telegram api returned status 400: 'Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 3781'\n"`

telepush error:
`2023/12/28 19:29:28 error: telegram api returned status 400: 'Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 3781'`

Thx for advance!

**Comment by muety** [comment]
This error usually occurs when the text you're sending contains reserved Markdown characters without actually being Markdown, e.g. when there is an underscore (`_`) (standing for italic text in Markdown) without a second, "closing" underscore. Normally, these characters should get escaped, but not sure, if they're actually all being covered. Can you check if your text contains anything unusual? Perhaps even post it here, if not containing any sensitive data?

**Comment by darkfessing** [comment]
Looks like I need to capture alertmanager notifications some way. Not really sure hot to do that. Is notification captured by telegram from:
```
telegram_configs:
          parse_mode: ''
```
is what we need?

This is it: 
`ts=2023-12-28T20:23:28.805Z caller=telegram.go:85 level=warn integration=telegram msg="Truncated message" alert="{}:{alertname=\"HostCpuIsUnderutilized\", instance=\"172.16.1.177:9100\", namespace=\"prometheus-stack\", severity=\"info\"}" max_runes=4096`
 
Notification:
[error.txt](https://github.com/muety/telepush/files/13789316/error.txt)

**Comment by muety** [comment]
I created #67, which will solve your problem. Will hopefully get to implementing this very soon!
